spring:
    thymeleaf:
        cache: false
weather:
    uri: "http://wthrcdn.etouch.cn/weather_mini?"
    redisTimeOut: 1800
    jobTime: 1800

redis:
#    database: 0
    host: localhost
    port: 6379  
#    password:   
    # 连接池最大连接数（使用负值表示没有限制）  
    pool.max-active: 8  
    # 连接池最大阻塞等待时间（使用负值表示没有限制）  
    pool.max-wait: -1  
    # 连接池中的最大空闲连接  
    pool.max-idle: 8  
    # 连接池中的最小空闲连接  
    pool.min-idle: 0  
    # 连接超时时间（毫秒）  
    timeout: 0
  